import { Student, Institution, TeachingClass, AttendanceRecord, PaymentRecord, PerformanceRecord, TeacherSettings } from '../types';

export const INITIAL_SETTINGS: TeacherSettings = {
  teacherName: 'Prof. Ramesh Adhikari',
  email: 'ramesh.adhikari@gmail.com',
  phone: '+977 9841234567',
  qualification: 'M.Sc. Mathematics & Physics (TU)',
  specialization: 'Higher Mathematics, Physics & College Calculus',
  currency: 'Rs.',
  dateSystem: 'AD', // default, easy 1-click toggle to BS
  timeFormat: '12h',
  defaultClassDuration: 60,
  reminderDaysBeforeDue: 3,
  theme: 'light',
};

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    name: 'Aarav Sharma',
    grade: 'Grade 10 (SEE)',
    schoolOrCollege: 'St. Xavier’s School, Jawalakhel',
    contactNumber: '+977 9811223344',
    parentName: 'Binod Sharma',
    parentContact: '+977 9851098765',
    address: 'Baneshwor, Kathmandu',
    subjects: ['Compulsory Mathematics', 'Optional Mathematics'],
    tuitionType: 'individual',
    startDate: '2026-04-15',
    classFrequency: '6 days/week (Sun-Fri)',
    classDurationMinutes: 60,
    feeStructure: 'monthly',
    feeAmount: 14000,
    paymentMethod: 'eSewa',
    paymentDueDay: 5,
    notes: 'Preparing for SEE Board Exam. Very strong in Geometry, needs extra practice in Trigonometry.',
    status: 'active',
    createdAt: '2026-04-15T09:00:00Z',
  },
  {
    id: 'std-2',
    name: 'Prashant Thapa',
    grade: '+2 Science (Grade 11)',
    schoolOrCollege: 'Kathmandu Model College (KMC)',
    contactNumber: '+977 9801122334',
    parentName: 'Sunita Thapa',
    parentContact: '+977 9841987654',
    address: 'Shankhamul, Lalitpur',
    subjects: ['Physics', 'Mathematics'],
    tuitionType: 'group',
    groupName: '+2 Science Morning Batch',
    startDate: '2026-06-01',
    classFrequency: '5 days/week',
    classDurationMinutes: 75,
    feeStructure: 'monthly',
    feeAmount: 9500,
    paymentMethod: 'Bank Transfer',
    paymentDueDay: 10,
    notes: 'Group tuition with 3 peers. Target: IOE Engineering Entrance preparation.',
    status: 'active',
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'std-3',
    name: 'Sneha Shrestha',
    grade: '+2 Science (Grade 12)',
    schoolOrCollege: 'Prasadi Academy, Lalitpur',
    contactNumber: '+977 9860123456',
    parentName: 'Gopal Shrestha',
    parentContact: '+977 9851123789',
    address: 'Kumaripati, Lalitpur',
    subjects: ['Physics'],
    tuitionType: 'individual',
    startDate: '2026-05-10',
    classFrequency: '4 days/week (Sun, Tue, Thu, Sat)',
    classDurationMinutes: 60,
    feeStructure: 'monthly',
    feeAmount: 12000,
    paymentMethod: 'eSewa',
    paymentDueDay: 15,
    notes: 'Focused on Mechanics and Electromagnetism formulas.',
    status: 'active',
    createdAt: '2026-05-10T11:00:00Z',
  },
  {
    id: 'std-4',
    name: 'Rohan KC & Group',
    grade: 'A-Levels (AS Level)',
    schoolOrCollege: 'Rato Bangala School',
    contactNumber: '+977 9813456789',
    parentName: 'Deepak KC',
    parentContact: '+977 9841567890',
    address: 'Patan Dhoka, Lalitpur',
    subjects: ['Cambridge Pure Mathematics (P1 & P3)'],
    tuitionType: 'group',
    groupName: 'A-Level Cambridge Batch',
    startDate: '2026-07-01',
    classFrequency: '3 days/week (Sun, Tue, Thu)',
    classDurationMinutes: 90,
    feeStructure: 'hourly',
    feeAmount: 1200, // per hour
    paymentMethod: 'Khalti',
    paymentDueDay: 1,
    notes: 'Hourly rate group calculation based on monthly recorded hours.',
    status: 'active',
    createdAt: '2026-07-01T08:30:00Z',
  },
  {
    id: 'std-5',
    name: 'Bipana Karki',
    grade: 'Grade 9',
    schoolOrCollege: 'Budhanilkantha School',
    contactNumber: '+977 9803456789',
    parentName: 'Janak Karki',
    parentContact: '+977 9851044332',
    address: 'Maharajgunj, Kathmandu',
    subjects: ['Mathematics', 'Science'],
    tuitionType: 'individual',
    startDate: '2026-03-01',
    classFrequency: 'Per-class basis (Weekends)',
    classDurationMinutes: 90,
    feeStructure: 'per_class',
    feeAmount: 1000, // per class
    paymentMethod: 'Cash',
    paymentDueDay: 28,
    notes: 'Weekend intensive conceptual building.',
    status: 'active',
    createdAt: '2026-03-01T07:00:00Z',
  }
];

export const INITIAL_INSTITUTIONS: Institution[] = [
  {
    id: 'inst-1',
    name: 'Apex College / Trinity Int’l College',
    facultyOrGrade: '+2 Science (Grade 12)',
    subjects: ['Calculus & Vectors', 'Modern Physics'],
    section: 'Section B (Morning)',
    numberOfPeriods: 2,
    periodDurationMinutes: 45,
    workingDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    paymentStructure: 'monthly',
    rateAmount: 42000,
    extraClassRate: 900,
    startDate: '2026-04-01',
    contactPerson: 'Dr. Narayan Prasad (Principal)',
    contactNumber: '+977 1 4478901',
    notes: 'Morning shift 06:30 AM to 08:00 AM. 2 periods daily.',
    status: 'active',
    createdAt: '2026-04-01T06:00:00Z',
  },
  {
    id: 'inst-2',
    name: 'Kathmandu Model College (KMC)',
    facultyOrGrade: 'B.Sc. CSIT (1st Semester)',
    subjects: ['Calculus & Analytical Geometry'],
    section: 'CSIT Batch 2083',
    numberOfPeriods: 1,
    periodDurationMinutes: 50,
    workingDays: ['Sunday', 'Monday', 'Wednesday', 'Friday'],
    paymentStructure: 'per_period',
    rateAmount: 950, // Rs. 950 per period
    extraClassRate: 1100,
    startDate: '2026-05-15',
    contactPerson: 'Sanjay Shrestha (HOD Computer Science)',
    contactNumber: '+977 1 4223344',
    notes: '11:15 AM to 12:05 PM period. Paid monthly based on total periods taken.',
    status: 'active',
    createdAt: '2026-05-15T09:00:00Z',
  }
];

export const INITIAL_CLASSES: TeachingClass[] = [
  {
    id: 'cls-1',
    title: 'Trinity College - Morning +2 Physics & Math',
    type: 'college',
    institutionId: 'inst-1',
    subject: 'Physics & Higher Math',
    location: 'Trinity College Room 402, Dilli Bazar',
    feeStructure: 'monthly',
    feeAmount: 42000,
    durationMinutes: 90,
    scheduleDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    startTime: '06:30',
    endTime: '08:00',
    color: '#3b82f6', // blue
    startDate: '2026-04-14',
    notes: 'Morning college periods for Grade 12 Section B',
    isActive: true,
  },
  {
    id: 'cls-2',
    title: 'KMC College - B.Sc. CSIT Calculus',
    type: 'college',
    institutionId: 'inst-2',
    subject: 'Calculus & Analytical Geometry',
    location: 'KMC CSIT Hall B, Balkumari',
    feeStructure: 'per_period',
    feeAmount: 950,
    durationMinutes: 50,
    scheduleDays: ['Sunday', 'Monday', 'Wednesday', 'Friday'],
    startTime: '11:15',
    endTime: '12:05',
    color: '#8b5cf6', // purple
    startDate: '2026-05-02',
    notes: 'University course period',
    isActive: true,
  },
  {
    id: 'cls-3',
    title: 'Aarav Sharma - Opt & Comp Math (Home)',
    type: 'home_tuition',
    studentId: 'std-1',
    subject: 'Compulsory & Opt Mathematics',
    location: 'Student Residence, Baneshwor',
    feeStructure: 'monthly',
    feeAmount: 14000,
    durationMinutes: 60,
    scheduleDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    startTime: '16:00',
    endTime: '17:00',
    color: '#10b981', // emerald
    startDate: '2026-04-20',
    notes: 'SEE Mathematics tuition',
    isActive: true,
  },
  {
    id: 'cls-4',
    title: 'Sneha Shrestha - Physics Grade 12',
    type: 'home_tuition',
    studentId: 'std-3',
    subject: 'Physics',
    location: 'Student Residence, Kumaripati',
    feeStructure: 'monthly',
    feeAmount: 12000,
    durationMinutes: 60,
    scheduleDays: ['Sunday', 'Tuesday', 'Thursday', 'Saturday'],
    startTime: '17:30',
    endTime: '18:30',
    color: '#06b6d4', // cyan
    startDate: '2026-05-10',
    notes: '+2 Science Physics individual tuition',
    isActive: true,
  },
  {
    id: 'cls-5',
    title: 'A-Level Cambridge Math Group',
    type: 'home_tuition',
    studentId: 'std-4',
    groupName: 'A-Level Cambridge Batch',
    subject: 'Pure Mathematics P1 & P3',
    location: 'Teacher Home Study Room, Shankhamul',
    feeStructure: 'hourly',
    feeAmount: 1200,
    durationMinutes: 90,
    scheduleDays: ['Sunday', 'Tuesday', 'Thursday'],
    startTime: '19:00',
    endTime: '20:30',
    color: '#f59e0b', // amber
    startDate: '2026-06-01',
    notes: 'Group session with Rohan and 2 classmates',
    isActive: true,
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    date: '2026-08-15',
    classId: 'cls-1',
    type: 'college',
    institutionId: 'inst-1',
    targetName: 'Trinity College - Morning +2 Physics & Math',
    subject: 'Calculus & Vectors',
    startTime: '06:30',
    endTime: '08:00',
    durationMinutes: 90,
    periodsCount: 2,
    status: 'present',
    notes: 'Completed Vector Products and Coordinate geometry in 3D.',
    topicsCovered: 'Vector cross products and plane equations',
    recordedAt: '2026-08-15T08:05:00Z',
  },
  {
    id: 'att-2',
    date: '2026-08-15',
    classId: 'cls-3',
    type: 'home_tuition',
    studentId: 'std-1',
    targetName: 'Aarav Sharma',
    subject: 'Optional Mathematics',
    startTime: '16:00',
    endTime: '17:00',
    durationMinutes: 60,
    status: 'present',
    notes: 'Trigonometric identities solved correctly.',
    topicsCovered: 'Multiple angle formulas sin 2A, cos 2A',
    recordedAt: '2026-08-15T17:02:00Z',
  },
  {
    id: 'att-3',
    date: '2026-08-15',
    classId: 'cls-4',
    type: 'home_tuition',
    studentId: 'std-3',
    targetName: 'Sneha Shrestha',
    subject: 'Physics',
    startTime: '17:30',
    endTime: '18:30',
    durationMinutes: 60,
    status: 'present',
    notes: 'Electromagnetic induction numerical exercises.',
    topicsCovered: "Faraday's Law and Lenz's Law problems",
    recordedAt: '2026-08-15T18:35:00Z',
  },
  {
    id: 'att-4',
    date: '2026-08-14',
    classId: 'cls-1',
    type: 'college',
    institutionId: 'inst-1',
    targetName: 'Trinity College - Morning +2 Physics & Math',
    subject: 'Calculus & Vectors',
    startTime: '06:30',
    endTime: '08:00',
    durationMinutes: 90,
    periodsCount: 2,
    status: 'present',
    notes: 'Introduction to vectors',
    recordedAt: '2026-08-14T08:05:00Z',
  },
  {
    id: 'att-5',
    date: '2026-08-14',
    classId: 'cls-2',
    type: 'college',
    institutionId: 'inst-2',
    targetName: 'KMC College - B.Sc. CSIT Calculus',
    subject: 'Calculus & Analytical Geometry',
    startTime: '11:15',
    endTime: '12:05',
    durationMinutes: 50,
    periodsCount: 1,
    status: 'present',
    notes: "L'Hopital Rule and Indeterminate forms",
    recordedAt: '2026-08-14T12:10:00Z',
  },
  {
    id: 'att-6',
    date: '2026-08-14',
    classId: 'cls-3',
    type: 'home_tuition',
    studentId: 'std-1',
    targetName: 'Aarav Sharma',
    subject: 'Compulsory Mathematics',
    startTime: '16:00',
    endTime: '17:00',
    durationMinutes: 60,
    status: 'present',
    notes: 'Compound Interest formulas and word problems',
    recordedAt: '2026-08-14T17:05:00Z',
  },
  {
    id: 'att-7',
    date: '2026-08-13',
    classId: 'cls-5',
    type: 'home_tuition',
    studentId: 'std-4',
    targetName: 'A-Level Cambridge Math Group',
    subject: 'Pure Mathematics P1',
    startTime: '19:00',
    endTime: '20:30',
    durationMinutes: 90,
    status: 'present',
    notes: 'Differentiation chain rule & product rule',
    recordedAt: '2026-08-13T20:32:00Z',
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    type: 'tuition',
    studentId: 'std-1',
    targetName: 'Aarav Sharma',
    periodMonthYear: '2026-08',
    amountDue: 14000,
    amountPaid: 14000,
    remainingBalance: 0,
    paymentDate: '2026-08-04',
    dueDate: '2026-08-05',
    paymentMethod: 'eSewa',
    status: 'paid',
    referenceNote: 'eSewa Txn #ESEWA-992147 - Paid on time for Shrawan/Bhadra',
    receiptNumber: 'REC-2026-0801',
    recordedAt: '2026-08-04T15:30:00Z',
  },
  {
    id: 'pay-2',
    type: 'college_salary',
    institutionId: 'inst-1',
    targetName: 'Trinity College (+2 Science)',
    periodMonthYear: '2026-07',
    amountDue: 42000,
    amountPaid: 42000,
    remainingBalance: 0,
    paymentDate: '2026-08-02',
    dueDate: '2026-08-01',
    paymentMethod: 'Bank Transfer',
    status: 'paid',
    referenceNote: 'Nabil Bank Direct Salary Credit - July 2026 (Ashadh)',
    receiptNumber: 'SAL-2026-0701',
    recordedAt: '2026-08-02T10:15:00Z',
  },
  {
    id: 'pay-3',
    type: 'tuition',
    studentId: 'std-2',
    targetName: 'Prashant Thapa',
    periodMonthYear: '2026-08',
    amountDue: 9500,
    amountPaid: 5000,
    remainingBalance: 4500,
    paymentDate: '2026-08-10',
    dueDate: '2026-08-10',
    paymentMethod: 'Bank Transfer',
    status: 'partially_paid',
    referenceNote: 'Part payment Rs. 5,000 received. Balance Rs. 4,500 promised by 20th Aug.',
    receiptNumber: 'REC-2026-0802',
    recordedAt: '2026-08-10T11:45:00Z',
  },
  {
    id: 'pay-4',
    type: 'tuition',
    studentId: 'std-3',
    targetName: 'Sneha Shrestha',
    periodMonthYear: '2026-08',
    amountDue: 12000,
    amountPaid: 0,
    remainingBalance: 12000,
    paymentDate: '',
    dueDate: '2026-08-15',
    paymentMethod: 'eSewa',
    status: 'overdue',
    referenceNote: 'Tuition fee due on 15th Aug. Friendly reminder ready to copy.',
    receiptNumber: '',
    recordedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'pay-5',
    type: 'tuition',
    studentId: 'std-4',
    targetName: 'Rohan KC & Group',
    periodMonthYear: '2026-08',
    amountDue: 10800, // 9 hours * 1200
    amountPaid: 0,
    remainingBalance: 10800,
    paymentDate: '',
    dueDate: '2026-08-20',
    paymentMethod: 'Khalti',
    status: 'pending',
    referenceNote: 'Hourly group calculation for current month.',
    receiptNumber: '',
    recordedAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'pay-6',
    type: 'college_salary',
    institutionId: 'inst-2',
    targetName: 'Kathmandu Model College (KMC CSIT)',
    periodMonthYear: '2026-07',
    amountDue: 17100, // 18 periods * 950
    amountPaid: 17100,
    remainingBalance: 0,
    paymentDate: '2026-08-05',
    dueDate: '2026-08-05',
    paymentMethod: 'Bank Transfer',
    status: 'paid',
    referenceNote: 'Period payment settled for 18 lecture periods taken in Ashadh.',
    receiptNumber: 'SAL-2026-0702',
    recordedAt: '2026-08-05T14:00:00Z',
  }
];

export const INITIAL_PERFORMANCE: PerformanceRecord[] = [
  {
    id: 'perf-1',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    subject: 'Optional Mathematics',
    date: '2026-08-12',
    examName: 'First Terminal Pre-Board Exam',
    fullMarks: 100,
    obtainedMarks: 91,
    percentage: 91,
    grade: 'A+',
    homeworkStatus: 'Excellent',
    classParticipationScore: 5,
    weakTopics: ['Trigonometric Compound Angles'],
    strongTopics: ['Matrices', 'Coordinate Geometry', 'Vectors'],
    teacherRemarks: 'Excellent improvement! Maintained speed and clarity in matrix transformations.',
    recordedAt: '2026-08-12T18:00:00Z',
  },
  {
    id: 'perf-2',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    subject: 'Compulsory Mathematics',
    date: '2026-08-05',
    examName: 'Unit Test 2: Arithmetic & Sets',
    fullMarks: 50,
    obtainedMarks: 44,
    percentage: 88,
    grade: 'A',
    homeworkStatus: 'Completed',
    classParticipationScore: 4,
    weakTopics: ['Venn diagram multi-union word problems'],
    strongTopics: ['Compound Interest', 'VAT and Discount'],
    teacherRemarks: 'Good performance. Needs to re-check calculation steps before submitting.',
    recordedAt: '2026-08-05T17:30:00Z',
  },
  {
    id: 'perf-3',
    studentId: 'std-3',
    studentName: 'Sneha Shrestha',
    subject: 'Physics',
    date: '2026-08-08',
    examName: 'Grade 12 Physics Monthly Test',
    fullMarks: 75,
    obtainedMarks: 62,
    percentage: 82.67,
    grade: 'A',
    homeworkStatus: 'Completed',
    classParticipationScore: 4,
    weakTopics: ['Alternating Current Phasor Diagrams'],
    strongTopics: ['Electromagnetism', 'Wave Optics'],
    teacherRemarks: 'Solid grasp of fundamental laws. Practicing 5 past question papers recommended.',
    recordedAt: '2026-08-08T19:00:00Z',
  },
  {
    id: 'perf-4',
    studentId: 'std-2',
    studentName: 'Prashant Thapa',
    subject: 'Physics',
    date: '2026-08-02',
    examName: 'Mechanics & Rotational Dynamics Test',
    fullMarks: 50,
    obtainedMarks: 36,
    percentage: 72,
    grade: 'B+',
    homeworkStatus: 'Partially Completed',
    classParticipationScore: 3,
    weakTopics: ['Moment of inertia integrations', 'Conservation of angular momentum'],
    strongTopics: ['Newtonian mechanics', 'Circular motion'],
    teacherRemarks: 'Needs to dedicate 30 minutes daily to numerical problem solving.',
    recordedAt: '2026-08-02T16:00:00Z',
  }
];
